### ISSUE TITLE
LuxPython

### ISSUE THREAD

**Issue by huykent** [guybw/LuxPythonCard#3]
Dear guybw,

I hope this message finds you well. I would like to kindly request permission to use your integration "[LuxPython_DEV](https://github.com/guybw/LuxPython_DEV)" for my system setup. Please let me know how I can proceed, and feel free to send any necessary forms to understand my configuration better.

Thank you for your support and assistance.

Best regards,
huykent

**Comment by manhhc** [comment]
Hello guybw

I hope this message finds you well. I would like to kindly request permission to use your integration "[LuxPython_DEV](https://github.com/guybw/LuxPython_DEV)" for my system setup. Please let me know how I can proceed, and feel free to send any necessary forms to understand my configuration better.

Thank you for your support and assistance.

Best regards,

**Comment by guybw** [comment]
Please read the readme
